feat(cleanup): remove !important part 1
tzConnectBerlin/prediction-market-ui pull request #508
Opened 2021-08-26 14:00 UTC by cpooley

Part 1 of removing !important

2021-08-26 15:26 UTC, cpooley commented
The snapshot test for Footer, shows h3 as 3rem and h4 as 2.125rem, so it's taking it from mui and not our theme. What's the best way to change that?

2021-08-27 09:04 UTC, shekhar-shubhendu commented
> The snapshot test for Footer, shows h3 as 3rem and h4 as 2.125rem, so it's taking it from mui and not our theme. What's the best way to change that?

if you create a WrappedComponent with ThemeProvider set then it will work
example: https://github.com/tzConnectBerlin/prediction-market-ui/blob/d4c05adce0fb926b866d5ea271abbbeb6f77aef0/src/design-system/molecules/FormikTextField/FormikTextField.test.tsx#L80

2021-08-27 11:14 UTC, tlebon approved these changes

2021-08-27 12:22 UTC, shekhar-shubhendu approved these changes
LGTM

Feel free to merge. :)

2021-08-27 12:26 UTC, shmodarresi requested changes

2021-08-27 12:26 UTC, shmodarresi commented on src/design-system/atoms/Button/Button.tsx
> +      sx={customStyle}
Please remove **customStyle** of props and just use **sx**?

2021-08-27 13:41 UTC, cpooley commented on src/design-system/atoms/Button/Button.tsx
> +      sx={customStyle}
My last pr was about removing sx :D 
Does it cause problems?

2021-08-27 13:53 UTC, shmodarresi approved these changes

2021-08-27 14:28 UTC, merged