Feat/basic liq form
tzConnectBerlin/prediction-market-ui pull request #513
Opened 2021-08-30 15:48 UTC by tlebon

- [x] updated liquidity form to have basic interaction mode
- [x] adding advanced state and PoC of toggle (to be overwritten with Cynthias PR #512 )
- [x] probably some other random stuff

2021-08-31 09:44 UTC, shekhar-shubhendu requested changes
- Update PR title as per Contribution guide
- Resolve LGTM comments

2021-08-31 11:35 UTC, tlebon commented
> * Update PR title as per Contribution guide
> * Resolve LGTM comments

as mentioned the LGTM comment looks fine to me, it should stay

2021-08-31 11:49 UTC, tlebon commented
im just updating the remove liduidity as well now, there's some open changes.

2021-09-03 14:20 UTC, shekhar-shubhendu commented
- Tooltip broken: 
![image](https://user-images.githubusercontent.com/9253059/132019932-78b18dec-4e03-4555-ab37-c8f271c93ebf.png)

- Clicking Add Liquidity doesn't work
- Clicking Remove Liquidity doesn't work
- Wrong error message
![image](https://user-images.githubusercontent.com/9253059/132020198-00c02d35-dd0b-4db4-a17e-ce28eb1ca0a7.png)
- Translation broken (expectedWithdraw)
![image](https://user-images.githubusercontent.com/9253059/132020417-9ba41bb1-a65e-4e27-9173-42f7a191b4c4.png)
- Remove Liquidity Expected withdraw value seems wrong
![image](https://user-images.githubusercontent.com/9253059/132020554-4244715e-457b-4adf-9341-80a47fa5b836.png)

2021-09-06 09:37 UTC, shmodarresi submitted a review, later dismissed

2021-09-06 09:56 UTC, shekhar-shubhendu commented
![image](https://user-images.githubusercontent.com/9253059/132198865-884d34d6-c3dc-4ae9-9808-8f27ee80f5bd.png)

double `--`

2021-09-06 09:59 UTC, shekhar-shubhendu commented
Regression:

![image](https://user-images.githubusercontent.com/9253059/132199202-d98b1c12-54ca-46a2-84ab-499cbb4ad6d2.png)

- Yes/No tokens are not automatically filled.

2021-09-07 17:14 UTC, shekhar-shubhendu approved these changes, later dismissed

2021-09-08 09:35 UTC, shekhar-shubhendu approved these changes

2021-09-08 09:40 UTC, merged